modLoader="${mod_loader}"
loaderVersion="${loader_version}"
license="${mod_license}"

[[mods]]
modId="${modid}"
version="${mod_version}"
displayName="${mod_name}"
displayURL='TBD'
logoFile="logo.png"
credits="${mod_credits}"
description='''${mod_description}'''

# Base
[[dependencies."${modid}"]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${modid}"]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${modid}"]]
modId="azurelib"
mandatory=false
versionRange="${azurelib_version_range}"
ordering="BEFORE"
side="BOTH"